# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52b9f802eba05f5dc69a0545143fb70fc739c079412c33f3356a059b758ed7b29ffe798e595ddd15efc74194c29a073546711987ab55a3010b13fa70506cfc2e

test:
  secret_key_base: d37b7d1f3d64035ff93c3cefbe184fe567ae4f1cf001f79a994eddcd801d54802c1f11be5c15da2faea033ca93a7621146c102e95a3e2442a6a690b79405dd0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
